trigger:
- main  # Tự động kích hoạt pipeline khi có thay đổi ở nhánh "main"

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@1
  inputs:
    versionSpec: '3.x'  # Đảm bảo môi trường có Python cho Flutter

- task: UseFlutter@0
  inputs:
    channel: 'stable'

- script: |
    flutter pub get
    flutter test
    flutter build apk --release
  displayName: 'Build Flutter APK'
